### ISSUE TITLE
Error on copy of separate ressource folders when post processing

### ISSUE THREAD

**Issue by AlexPiro** [petrbroz/forge-convert-utils#11]
When ressources are in separate folders, I get an error in the post processing function to copy files from tmp -> destination folder because folders don't exist.
I made this change in the `src/gltf/writer.js` (line. 183) to make this work : 
`     for (const name of Object.getOwnPropertyNames(result.separateResources)) {
                        fse.ensureDirSync(path.dirname(path.join(outputFolder, name)));
			            fse.writeFileSync(path.join(outputFolder, name), result.separateResources[name]);
}`

**Comment by petrbroz** [comment]
Awesome, thanks @AlexPiro! Would you mind submitting a PR with the suggested code change?

**Comment by AlexPiro** [comment]
#12

**Comment by petrbroz** [comment]
Perfect, thanks so much!

**Comment by petrbroz** [comment]
Fixed by @AlexPiro in https://github.com/petrbroz/forge-convert-utils/pull/12.
