### ISSUE TITLE
converter - aborts when missing texture

### ISSUE THREAD

**Issue by wallabyway** [petrbroz/forge-convert-utils#16]
when running forge-convert on forge bucket object, where one of the textures is missing, the convert tool aborts.

instead, can it complete the conversion using a dummy texture ?

**Comment by petrbroz** [comment]
Sure, let me look into that. If I can't find any model with missing textures, would you mind sharing one with me?

**Comment by petrbroz** [comment]
How about this: https://github.com/petrbroz/forge-convert-utils/commit/584eda97039bc98b802637131ef5ab2de475166e?

**Comment by petrbroz** [comment]
Fixed in https://github.com/petrbroz/forge-convert-utils/tree/v2.0.1.
