### ISSUE TITLE
Document the use of Forge metadata

### ISSUE THREAD

**Issue by petrbroz** [petrbroz/forge-convert-utils#19]
Explain how the gltf elements can be linked to the original model metadata in Forge, e.g.:

- using https://forge.autodesk.com/en/docs/model-derivative/v2/reference/http/urn-metadata-guid-properties-GET
- by downloading the property db in sqlite: https://github.com/petrbroz/forge-convert-utils/blob/develop/bin/forge-convert.js#L85
- by parsing the property db in _object*.json.gz_ files: https://github.com/petrbroz/forge-convert-utils/blob/develop/test/remote-svf-props.js#L21-L22

**Comment by petrbroz** [comment]
Addressing https://twitter.com/FlorolF_/status/1226769610504130560

**Comment by wallabyway** [comment]
Use this SELECT statement when querying the sqlite db file.   https://github.com/wallabyway/propertyServer/blob/master/pipeline.md

You can do the same thing with the 5 JSON files, but it's a little bit harder...  (see the diagram in the link)

**Comment by florolf1** [comment]
Thanks, i will give it a try!
