### ISSUE TITLE
Question regarding Large file size

### ISSUE THREAD

**Issue by UmeshDharmik** [petrbroz/forge-convert-utils#26]
We are using forge-convert-utils to convert Revit file from Forge OSS buckets to GLTF.
Our Revit file is of size 25MB, but the converted GLTF model is 53 MB after download.

We have other models of size around 200MB. After converting to GLTF , size of GLTF goes upto 600 MB. 
We would like to use these GLTF models in our AR application.Having large file size makes it difficult to work with.

Could the size of the model be reduced, such that the GLTF size is around the original file size or smaller.

**Note** : We can not use draco decompression in our AR module.

**Comment by petrbroz** [comment]
Unfortunately there is no guarantee that the size of the glTF output will correlate with the input Revit model. The two formats are just fundamentally different. Here's some ideas on what to try:

- use the [deduplicate](https://github.com/petrbroz/forge-convert-utils/blob/develop/src/gltf/writer.ts#L24) feature - the conversion into glTF will take more time, but it could potentially detect duplicate geometries and decrease the glTF size by instancing them
- try the (experimental) [OTG-to-glTF](https://github.com/petrbroz/forge-convert-utils/blob/develop/samples/remote-otg-to-gltf.js) pipeline; the OTG format itself is already deduplicating geometries heavily
- if Draco is not an option, consider using [gltfpack](https://github.com/zeux/meshoptimizer/blob/master/gltf/README.md)
- customize the converter to only output a subset of the input file's content (for example, [by area](https://github.com/petrbroz/forge-convert-utils/blob/develop/samples/filter-by-area.js)), and generate multiple glTF files for your Revit model
