### ISSUE TITLE
DWG -> SVF: Name and Layer Information

### ISSUE THREAD

**Issue by jackcaron** [petrbroz/forge-convert-utils#29]
So with Forge, I can easy get the name and layer information from the properties listing.

But once it's in an SVF, to extract the geometry, it's a bit less obvious how to map each piece of mesh/geometry in the SVF to the original one in the DWG file.

I know those names and layers are preserved somewhere in the SVF, can see them being listed in the PropertyDB's `_vars` object.

**Comment by jackcaron** [comment]
Found it
There's a bug in the ` getProperties` function in the `src/common/propdb-reader.ts`, the `category` can potentially be `null/undefined` it must be checked in the `if (prop.category.match(/^__\w+__$/)) {` before calling match!

**Comment by petrbroz** [comment]
Thanks Jack. Let me reopen this issue to make sure that the `prop.category` is checked for `null/undefined` first.
