### ISSUE TITLE
Center models that require double precision & store offset

### ISSUE THREAD

**Issue by FreakTheMighty** [petrbroz/forge-convert-utils#47]
When using the `--center` option it would be helpful to recover the offset. Perhaps the value could be stored inside the glTF using [this cesium extension](https://github.com/KhronosGroup/glTF/tree/main/extensions/1.0/Vendor/CESIUM_RTC)

---

Adding a bit more context:

Models that are very far from the origin suffer from rendering artifacts after being converted to glTf. The typical solution is to offset large (double precision) values in the model into a more reasonable floating point range then storing that offset to recover the double precision values later.

**Example of rendering artifacts when using forge and forge-convert-utils to go IFC -> SVF -> GLB**
 ![image-20220311-155844](https://user-images.githubusercontent.com/247092/157903252-fb7b001e-7933-4b12-82d2-0e5026a4d624.png)

**Comment by wallabyway** [comment]
isn't the offset stored in the parent glTF node, when you add the --center option?

we could duplicate this same value, into the cesium extension...

"extensions": {
    "CESIUM_RTC": {
        "center": [6378137.0, 0.0, 0.0]
    }
}

would that work?

**Comment by FreakTheMighty** [comment]
@wallabyway thanks for the feedback. I haven't checked the root node, but I would hope that the transform is __not__ applied to the root node as very large transforms need to be handled in a special way by many real time rendering engines. For example, in Unity if we apply a 6378137.0 unit translation the model will appear to jump erratically as the engine only support single precision floats.

Instead, we would like the model very close to the origin and have the offset stored elsewhere incase we need to perform a coordinate system mapping.

**Comment by FreakTheMighty** [comment]
@wallabyway , but it does look like you're right https://github.com/petrbroz/forge-convert-utils/blob/ab7057ba1ad465b725667873320fa2d9a745cbfd/src/gltf/writer.ts#L226-L242

Perhaps we need an additional option as I can see how this option could be valuable for different use cases. For large offsets the offset needs to be applied either to the individual node's transforms, or in some cases the mesh data itself.

**Comment by wallabyway** [comment]
The vertices and node matrix offset, should be normalized.  ie. The 16bit float precision in the vertices, should be maximized around the origin, with offsets moved into the 32bit float precision in the node matrix.

Is this not the case?  Perhaps you have an example?

**Comment by FreakTheMighty** [comment]
@wallabyway I was with you right up until you said it shod be moved into the 32 but float node matrix. I think it should go into the extension to avoid having 16bit precision rendering engines from applying the transform.

With regards to the normalization I think it can be a bit complicated cause the translation could happen anywhere in the hierarchy all the way down to vertices. The easier thing is to bake the transforms into the vertices then normalize, but this means losing relative transforms.

**Comment by petrbroz** [comment]
I think what @wallabyway is referring to is using a 3x3 matrix of `float`s representing rotation and scale, together with 3 `double`s representing the offset. I'm not sure if Unity does that, though.

@FreakTheMighty do you have any sample SVF that would demonstrate this issue (glTF geometry being "wobbly" due to floating point precision issues in Unity)?

**Comment by wallabyway** [comment]
@FreakTheMighty - We have drifted from the main point of this feature request.

Let's leave this issue, "center a glTF" to origin, as a way to fix the Three.exportUSDz this issue...
https://github.com/wallabyway/quicklook-example
This fix will also center things for other views like gltf-viewer, sandbox Babylon.js and LGLTracer.

@petrbroz has a branch with the fix - but I haven't tested it yet.  Then we can close this issue.


In the meantime, could you create a new issue, which asks for cesium_RTC support ?

Maybe what you are looking for is 3D-Tiles-Next ?

To get a very large offset, at planet scale and high precision, create a tileset.json file, put in two glTF file references, and position each glTF with crazy large offsets.

Treat 3D-Tiles-Next as like a scene description of your glTFs.

**Comment by FreakTheMighty** [comment]
Apologies for the delay. I have some screenshots to share, but I still need to get approval for the source files. I will post files as soon as I have approval.

| Source | Rendering | Viewer |
| ----------- | ----------- | ----------- |
| IFC (original) | ![image-20220311-155656](https://user-images.githubusercontent.com/247092/157903139-84edc3ee-8f8b-4a9f-8b6b-9a4408f5763e.png) | BIM Vision |
| GLB no centering | ![image-20220311-155844](https://user-images.githubusercontent.com/247092/157903252-fb7b001e-7933-4b12-82d2-0e5026a4d624.png)| https://sandbox.babylonjs.com/ |
| GLB centered | ![image-20220311-155744](https://user-images.githubusercontent.com/247092/157903362-3b0070a0-31bf-47e5-9cad-a47821950e52.png)| https://sandbox.babylonjs.com/ |


----

@wallabyway we use 3d tiles (v1) elsewhere in our product, but for this tool it feels a little heavy handed to require the authoring of a `tileset.json` especially if this project isn't intending to support more features from the spec. With that said, it is unclear what the status of `CESIUM_RTC` is as it was originally authored against gltf 1.0 4 years ago. 🤷 maybe the most "standard" and modern approach would be to spit out a tileset.json that uses the new [3DTILES_content_gltf](https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_content_gltf)

**Comment by FreakTheMighty** [comment]
@petrbroz @wallabyway I've attached two zip files. The first contains an source IFC and two resulting glbs after undergoing` IFC-> SVF -> GLB conversion`. One of the GLB's has been converted with the `--center` option the other without. Not that both display floating precision artifacts, but without `--center` the GLB renders with new artifacts any time a the camera moves.

[Test_View_ifc_and_glb.zip](https://github.com/petrbroz/forge-convert-utils/files/8245413/Test_View_ifc_and_glb.zip)
[svf_output.zip](https://github.com/petrbroz/forge-convert-utils/files/8245414/svf_output.zip)


| Source | Rendering | Viewer |
| ----------- | ----------- | ----------- |
| IFC (original) |![image](https://user-images.githubusercontent.com/247092/158187411-c8a7de51-bc1c-432c-9a74-c74b181e9e40.png) | BIM Vision |
| GLB no centering| ![image](https://user-images.githubusercontent.com/247092/158187335-1f459db8-6816-41f7-9666-d7b6940d32d0.png)| https://sandbox.babylonjs.com/ |
| GLB centered |![image](https://user-images.githubusercontent.com/247092/158187641-2ccbb916-632f-418e-8fd2-a4a1931a4880.png)| https://sandbox.babylonjs.com/ |

**Comment by FreakTheMighty** [comment]
@petrbroz I want to note two challenges for offsetting models with these sorts of large distances.

1. Large values can exist anywhere in the transformation hierarchy all the way down to the individual vertices. I don't imagine this is "best practice", but I received  a customer file that was very far from the origin, but where there were only identity transforms and each vertices had very large values. This makes determining an appropriate offset and figuring out where it should be applied a little less straight forward.
2. I haven't run into this, but of course you could have a file where no offset would produce good results for the whole file. For example, a file that contains two sites that are very far apart.

**Comment by wallabyway** [comment]
@FreakTheMighty  - Looks fine in three.js 
Something is wrong with babylon.js... Hmmm 🤔 

**Validation Report Errors:**
1. bad accessors from the report. I wonder what that is ?
2. it says 'Generator: forge-convert-utils' , yet forge-convert-utils doesn't save glb.  What tool did you use to convert glTF  into this glb ?  It's not reporting itself.

![Screen Shot 2022-04-08 at 12 21 00 PM](https://user-images.githubusercontent.com/440241/162510242-d9accc1b-3808-490a-b5ea-26c767f77b10.JPG)
)

**Comment by FreakTheMighty** [comment]
@wallabyway a colleague generated those glbs, so I'll need to get back to you on how they were generated. Meanwhile, I've regenerated from the attached SVF and I'm attaching the original gltf as output from `forge-convert`.

[0.zip](https://github.com/petrbroz/forge-convert-utils/files/8454894/0.zip)
[centered-0.zip](https://github.com/petrbroz/forge-convert-utils/files/8454903/centered-0.zip)

 ---

With regards to the three.js working, while babylon.js doesn't, I'm pretty curious to understand why. With that said, I think the glTF spec is pretty clear, the matrix in the node is stored as a float, not double. I think this is confusing cause technically JSON can store doubles, but the glTF specifies float.

https://github.com/KhronosGroup/glTF/blob/8e798b02d254cea97659a333cfcb20875b62bdd4/specification/2.0/schema/node.schema.json#L27-L36

I think this is pretty important to us though, cause even if we put an offset in transform not all viewers will handle it correctly and some will handle it very badly :D.

**Comment by bghgary** [comment]
> I think the glTF spec is pretty clear, the matrix in the node is stored as a float, not double.

I'm not sure what you are reading that indicates this. The referenced schema says `floating-point` values which doesn't indicate single-precision or double-precision. I will see if I can determine what Babylon.js is doing.

**Comment by FreakTheMighty** [comment]
@bghgary perhaps I’ve misread or conflated those terms. In C# the types float vs double denote precision. Also, in the spec regarding accessors it does say it is limited to single precision. 

https://github.com/KhronosGroup/glTF/blob/8e798b02d254cea97659a333cfcb20875b62bdd4/specification/2.0/Specification.adoc#3622-accessor-data-types

The other reason I thought it was single precision is because I thought webgl has single precision limitation. Issues like this seem to point to the problem and workaround’s https://github.com/mapbox/mapbox-gl-js/issues/7268#issuecomment-420711536

**Comment by bghgary** [comment]
It's very likely the issue is because of single-precision issues. Babylon.js will eventually use the matrix as floats in the shader. I'm just noting that `floating-point` doesn't imply single-precision. The accessor data types are for accessors. The matrix you are referring to are stored as JSON properties which are not accessors. Maybe @lexaknyazev can help us with this part. @lexaknyazev Is there a restriction on what kind of float values are accepted in the matrix property of a node?

**Comment by FreakTheMighty** [comment]
https://github.com/KhronosGroup/glTF/issues/2140#issuecomment-1093975959

I think this answers the question about the spec pretty clearly, but doesn’t exactly answer how to deal with the problem at hand. I have limited control over how an engine handles these values.

**Comment by javagl** [comment]
I stumbled over this via the linked issue, and without knowing much of the _specific_ context here (and sorry if this hint is already obsolete) : 

- The initial post suggested using the `CESIUM_RTC` extension. This was an extension for glTF **1.0**, supposed to address the issues that are described in more detail in the [Precisions, Precisions](https://help.agi.com/AGIComponents/html/BlogPrecisionsPrecisions.htm) article that is linked there as well
- The latest recommendation for handling "large transforms", at least from Cesium, is to integrate these transforms into the translation component of the root node of the asset

<sup>(I don't have the perfect place to link to for the latter - fow now, it is [just one side note in the spec](https://github.com/CesiumGS/3d-tiles/blob/c4b1e234e4d7ecb70bcb9210d67f3647b500a706/specification/TileFormats/glTF/README.md#batched-3d-model-b3dm) )</sup>

And this indeed _does_ raise the question of what a rendering engine will do when the translation contains a value that is "too large for `float` (but not too large for `double`)" - it boils down to some trickery when passing the data to the GPU, but that has to be sorted out by the rendering experts...

**Comment by deltakosh** [comment]
Hey team! I've been investigating this issue and I have a way to fix it.

When creating the Babylon Engine, we enable it with 32bits precision matrices. With very large numbers like here it is not enough. We picked 32bits first for perf reasons of course.

The solution is to use 64 bits. To do so, simply initialize the engine with this line:
```
this._engine = new Engine(this._canvas, antialias, {
    seHighPrecisionMatrix: true
});
```

The output:
![image](https://user-images.githubusercontent.com/1306056/163012413-5ad84f20-c768-4c38-912e-3765d19a6018.png)

**Comment by deltakosh** [comment]
By the way I noticed that the glb file has a lot of errors:
![image](https://user-images.githubusercontent.com/1306056/163012677-eff535a4-05ed-4885-bcc2-73edc36c2428.png)

**Comment by deltakosh** [comment]
Update: We decided to switch the Sandbox to 64bits precision by default ;)

**Comment by Popov72** [comment]
Could be relevant: https://github.com/BabylonJS/Babylon.js/issues/4516#issuecomment-769069062

**Comment by deltakosh** [comment]
Sandbox update is live

**Comment by FreakTheMighty** [comment]
@petrbroz @wallabyway I think this ticket could be closed. It does seems like best practice is to put the offset into the root node and that its up to the viewer to handle this well.

**Comment by petrbroz** [comment]
Sorry to chime in this late guys. It looks like a lot has been discussed here. So if I understand it correctly, there's no need to address the double-precision issue in the converter, but we still need to figure out what the validation issues are. I will look into that next week.
