### ISSUE TITLE
Hierarchy and Name Issue

### ISSUE THREAD

**Issue by ffreality** [petrbroz/forge-convert-utils#52]
Converted GLTF/GLB files don't preserve its mesh hierarchy and names.
Example CAD convert workflow

IAM > SVF (Forge API) > GLB (Forge Convert Utils) but all assemblies gone. I just have numbered static mesh components.

**Comment by wallabyway** [comment]
Hi ffreality...
The dbid's are preserved in the gltf nodes.

The hierarchy is stored in a instance tree json file, a separate file.

The leaf nodes in that instance tree json file, have dbid's which correlate to the gltf node dbids.

So everything is there, it's just not documented anywhere.
![Screen Shot 2022-02-22 at 2 22 04 PM](https://user-images.githubusercontent.com/440241/155230580-eaef4687-1162-4ea1-98d6-8d26b34c392c.JPG)

![Screen Shot 2022-02-22 at 2 22 42 PM](https://user-images.githubusercontent.com/440241/155230667-c8993ff0-5e15-425e-8140-09ab26f273f9.JPG)

**Comment by petrbroz** [comment]
Yep, the SVF file format stores all geometries in a flat list, and it then provides a logical hierarchy on top of these geometries in a separate data structure. When converting SVF files to the glTF format we keep the flat list but you are free to add the logical hierarchy to your application if you want to, for example, by retrieving the hierarchy from the [GET	{urn}/metadata/{guid}](https://forge.autodesk.com/en/docs/model-derivative/v2/reference/http/urn-metadata-guid-GET/) endpoint, and linking the dbIDs in the hierarchy to the dbIDs in the glTF (they're embedded into the node names).
