### ISSUE TITLE
Separate buffers using Draco compression

### ISSUE THREAD

**Issue by AlexPiro** [petrbroz/forge-convert-utils#7]
When using the draco compression extension, buffers are embed into the gltf file which is not the case when not using this extension.
When using the gltf-pipeline, "separate option" is always "false" in your code :
`if (this.compress || this.binary) {
           this.log('Post-processing gltf output...');
            const options: any = {
                resourceDirectory: this.baseDir,
                separate: false,
                separateTextures: false,
                stats: false,
                name: 'output'
            };
            if (this.compress) {
                options.dracoOptions = {
                    compressionLevel: 10
                };
            }`

This should be very useful for importers that does not support embed buffers (cf. GLTF Fast for Unity.

**Comment by petrbroz** [comment]
Sure, we can change that. What's your suggestion? Perhaps using `separate: true` when `this.binary === false`, and using `separate: false` when `this.binary === true`?

**Comment by AlexPiro** [comment]
Yes, it seems good from my point of view !
